/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangdg_ffmepg4android_VideoFixUtils */

#ifndef _Included_com_jiangdg_ffmepg4android_VideoFixUtils
#define _Included_com_jiangdg_ffmepg4android_VideoFixUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangdg_ffmepg4android_VideoFixUtils
 * Method:    getVideoAngle
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiangdg_ffmepg4android_VideoFixUtils_getVideoAngle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jiangdg_ffmepg4android_VideoFixUtils
 * Method:    excuteFFMPEGCmd
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiangdg_ffmepg4android_VideoFixUtils_excuteFFMPEGCmd
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
